name: ci

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Execute permission 🎉
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          script: |
            cd /home/eling/projek/hariakhir
            sudo git stash
            sudo git pull origin develop
            sudo pm2 restart /home/eling/projek/hariakhir/main.py
            sudo chmod -R 777 /home/eling/projek/hariakhir